# Generated by Django 4.1.7 on 2023-03-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studdata',
            name='sem',
        ),
    ]
