# Generated by Django 4.1.7 on 2023-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_teacherdata_remove_teachdata_officephone"),
    ]

    operations = [
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("question", models.CharField(max_length=100)),
                ("op1", models.CharField(max_length=100)),
                ("op2", models.CharField(max_length=100)),
                ("op3", models.CharField(max_length=100)),
                ("op4", models.CharField(max_length=100)),
                ("correct", models.CharField(max_length=100)),
                ("diff", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="teachData",
        ),
    ]
