# Generated by Django 4.1.7 on 2023-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_test_alter_questions_op1_alter_questions_op2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("qno", models.IntegerField()),
                ("datee", models.DateField()),
            ],
        ),
    ]
